model:
  provider: zhipuai
  model: glm-4-flash
  api_key: "@get api_key"

server:
  instances:
    - name: calculate
      description: ''
      script: "calculate_server.py"

    - name: hello
      description: ""
      script: "hello_server.py"

