env: dev

model:
  provider: zhipuai
  model: glm-4-flash
  api_key: "@get api_key"

database:
  redis:
    host: localhost
    port: 6379

  mongodb:
    host: localhost
    port: 27017
    db: agent

log:
  dir: ./logs
  level: INFO
  rotation: 100MB
  retention: 10

server:
  instances:
    - name: calculate
      description: "提供两个数字的加、减、乘、除四则运算"
      script: "calculate_server.py"
