env: dev

model:
  provider: zhipuai
  model: glm-4-flash
  api_key: "@get api_key"

server:
  instances:
    - name: calculate
      description: "提供两个数字的加、减、乘、除四则运算"
      script: "calculate_server.py"

#    - name: hello
#      description: ""
#      script: "hello_server.py"

