model:
  provider:
  model:
  api_key:
  generation:
server:
  instances:
  - name: ''
    description: ''
    script: ''
    args: []
    env: {}
    cwd:
  - name: ''
    description: ''
    url: ''
    headers: {}
    auth:
